[build]
publish = "staticfiles"
command = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn fullstack_bike.wsgi --log-file -"

[build.environment]
DATABASE_URL = "postgres://username:password@hostname:port/dbname"
DEBUG = "False"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
