# Generated by Django 4.1 on 2024-06-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="stock",
            field=models.IntegerField(default="10"),
            preserve_default=False,
        ),
    ]
