services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn fullstack_bike.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres:OapQRQvlFsZgUYEVzSGGqruACiQwPwvB@viaduct.proxy.rlwy.net:44818/railway"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
